---

- name: Change mailname
  copy:
    content: "{{ basic_mail_name }}"
    dest: "/etc/mailname"
    mode: "0644"
    owner: root
    group: root
  when: basic_mail_name is defined and basic_mail_name

- name: Add aliases for mail redirection
  lineinfile:
    dest: /etc/aliases
    regexp: '^root:'
    line: 'root: {{ basic_redirect_root_mail }}'
    state: present
  when: basic_redirect_root_mail is defined and basic_redirect_root_mail
