---

- name: Ensure epel-release is present (CentOS 7)
  package:
    name:
      - epel-release
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- name: Update cache and install mandatory package (Debian)
  apt:
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: Install mandatory packages
  package:
    name: "{{ basic_mandatory_packages }}"

- name: Install common packages
  package:
    name: "{{ basic_common_pakages }}"

- name: Install extra packages
  package:
    name: "{{ basic_extra_packages }}"
    state: present

- name: Ensure Python2 lib are presents (CentOS 7)
  package:
    name:
      - python-setuptools
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- name: Install pip packages
  pip:
    executable: pip3
    name: "{{ basic_pip_packages }}"
    state: present
