---

- name: Ensure epel-release is present (CentOS 7)
  package:
    name:
      - epel-release
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- name: Update cache and install mandatory package (Debian)
  apt:
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: Install mandatory packages
  package:
    name: "{{ basic_mandatory_packages }}"

- name: Install common packages
  package:
    name: "{{ basic_common_pakages }}"

- name: Set specific packages based on Ubuntu version
  set_fact:
    specific_packages: >-
      {{ ubuntu_22_packages if ansible_distribution == 'Ubuntu' and ansible_distribution_version == '22' else
         ubuntu_24_packages if ansible_distribution == 'Ubuntu' and ansible_distribution_version == '24' else [] }}

- name: Install common and specific packages
  package:
    name: "{{ basic_common_pakages + specific_packages }}"
    state: present

- name: Ensure Python2 lib are presents (CentOS 7)
  package:
    name:
      - python-setuptools
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- name: Install pip packages with extra args for Ubuntu 24
  pip:
    executable: pip3
    name: "{{ basic_pip_packages }}"
    state: present
    extra_args: --break-system-packages
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '24'

- name: Install pip packages
  pip:
    executable: pip3
    name: "{{ basic_pip_packages }}"
    state: present
  when: not (ansible_distribution == 'Ubuntu' and ansible_distribution_version == '24')
