---

- name: Disallow password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^(# *)?PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: Restart ssh

- name: Disallow root SSH access
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^(# *)?PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: Restart ssh

- name: Allow agent forwarding
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^(# *)?AllowAgentForwarding"
    line: "AllowAgentForwarding yes"
    state: present
  notify: Restart ssh

- name: Allow tcp forwarding
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^(# *)?AllowTcpForwarding"
    line: "AllowTcpForwarding yes"
    state: present
  notify: Restart ssh
