---

- name: Configure listchanges
  lineinfile:
    dest: /etc/apt/listchanges.conf
    regexp: '^which='
    line: 'which=both'
    state: present

- name: Enable APT automatic update
  template:
    src: unattended-upgrade/02periodic.j2
    dest: /etc/apt/apt.conf.d/02periodic
    mode: "0644"
    owner: root
    group: root

- name: Adjust APT automatic update configuration
  template:
    src: unattended-upgrade/50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: "0644"
    owner: root
    group: root
