---

- name: Restart journald
  service:
    name: systemd-journald
    state: restarted

- name: Restart ssh
  service:
    name: "{{ 'ssh' if ansible_facts['os_family'] == 'Debian' else 'sshd' }}"
    state: reloaded
