---

- name: Restart journald
  service:
    name: systemd-journald
    state: restarted

- name: Populate service facts
  ansible.builtin.service_facts:

- name: Restart ssh
  service:
    name: "{{ 'sshd' if 'sshd' in ansible_facts.services else 'ssh' }}"
    state: reloaded
