---
- name: Converge
  hosts: instance
  become: true
  roles:
    - role: "steamulo.basic"
      vars:
        basic_hostname: instance
        basic_redirect_root_mail: admin@example.com
        basic_hosts_unsafe_writes: true
        basic_passwordless_sudo: true
        basic_sudo_users:
          - user: test_sudo_user
            authorized_keys:
              - ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQB/nAmOjTmezNUDKYvEeIRf2YnwM9/uUG1d0BYsc8/tRtx+RGi7N2lUbp728MXGwdnL9od4cItzky/zVdLZE2cycOa18xBK9cOWmcKS0A8FYBxEQWJ/q9YVUgZbFKfYGaGQxsER+A0w/fX8ALuk78ktP31K69LcQgxIsl7rNzxsoOQKJ/CIxOGMMxczYTiEoLvQhapFQMs3FL96didKr/QbrfB1WT6s3838SEaXfgZvLef1YB2xmfhbT9OXFE3FXvh2UPBfN+ffE7iiayQf/2XR+8j4N4bW30DiPtOQLGUrH1y5X/rpNZNlWW2+jGIxqZtgWg7lTy3mXy5x836Sj/6L
            password: "$1$Q4zVybvT$7f9ZBJ9mC2eqzXRWYFc5D." # password
        basic_standard_users:
          - user: test_standard_user
            authorized_keys:
              - ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQB/nAmOjTmezNUDKYvEeIRf2YnwM9/uUG1d0BYsc8/tRtx+RGi7N2lUbp728MXGwdnL9od4cItzky/zVdLZE2cycOa18xBK9cOWmcKS0A8FYBxEQWJ/q9YVUgZbFKfYGaGQxsER+A0w/fX8ALuk78ktP31K69LcQgxIsl7rNzxsoOQKJ/CIxOGMMxczYTiEoLvQhapFQMs3FL96didKr/QbrfB1WT6s3838SEaXfgZvLef1YB2xmfhbT9OXFE3FXvh2UPBfN+ffE7iiayQf/2XR+8j4N4bW30DiPtOQLGUrH1y5X/rpNZNlWW2+jGIxqZtgWg7lTy3mXy5x836Sj/6L
            groups:
              - bar
        basic_time_zone: "Etc/UTC"
        basic_locale: "en_US.UTF-8"
        basic_locale_list:
          - "fr_FR.UTF-8"
          - "fr_LU.UTF-8"
          - "ar_IN.UTF-8"
          - "ga_IE.UTF-8"
