---
scenario:
  name: default
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  ansible-lint -v
  flake8
platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-ubuntu2204}
    dockerfile: ../docker/Dockerfile-${MOLECULE_DISTRO:-ubuntu2204}
    pre_build_image: false
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: "/lib/systemd/systemd"
provisioner:
  name: ansible
  env:
    ANSIBLE_REMOTE_TMP: /tmp/ansible
    ANSIBLE_REMOTE_USER: root
  config_options:
    defaults:
      remote_tmp: /tmp/ansible
      allow_world_readable_tmpfiles: true
verifier:
  name: testinfra
  options:
    sudo: true
